package com.posapp.ui;

import com.posapp.dao.CustomerDAO;
import com.posapp.model.Customer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

public class CustomerForm extends JPanel {

    // ── Generated by IntelliJ - DO NOT redeclare ──────────────────────
    private JPanel mainPanel;
    private JPanel panelHeader;
    private JPanel panelFields;
    private JPanel panelSearch;
    private JPanel panelButtons;
    private JPanel panelTable;
    private JTextField txtName;
    private JTextField txtPhone;
    private JTextField txtSearch;
    private JButton btnSearch;
    private JButton btnAdd;
    private JButton btnUpdate;
    private JButton btnDelete;
    private JButton btnClear;
    private JTable tblCustomers;
    private JTextField txtDiscount;
    // ──────────────────────────────────────────────────────────────────

    private final CustomerDAO customerDAO = new CustomerDAO();
    private int selectedCustomerId = -1;

    public CustomerForm() {
        setLayout(new BorderLayout());
        add(mainPanel, BorderLayout.CENTER);

        setupTable();
        loadAllCustomers();
        setupButtons();
        setupTableClickListener();
    }

    // ── Set up JTable columns and style ───────────────────────────────
    private void setupTable() {
        String[] columns = {"ID", "Customer Name", "Phone Number", "Discount (%)"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblCustomers.setModel(model);
        tblCustomers.setDefaultEditor(Object.class, null); // read-only

        tblCustomers.setRowHeight(28);
        tblCustomers.setFont(new Font("SansSerif", Font.PLAIN, 12));
        tblCustomers.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        tblCustomers.getTableHeader().setBackground(new Color(26, 58, 107));
        tblCustomers.getTableHeader().setForeground(Color.WHITE);
        tblCustomers.setSelectionBackground(new Color(232, 240, 250));
        tblCustomers.setGridColor(new Color(230, 230, 230));

        tblCustomers.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        tblCustomers.getColumnModel().getColumn(1).setPreferredWidth(200); // Name
        tblCustomers.getColumnModel().getColumn(2).setPreferredWidth(130);// Phone
        tblCustomers.getColumnModel().getColumn(3).setPreferredWidth(90); // Discount
    }

    // ── Load all customers into the table ─────────────────────────────
    private void loadAllCustomers() {
        populateTable(customerDAO.getAllCustomers());
    }

    // ── Fill table rows from a list of customers ──────────────────────
    private void populateTable(List<Customer> customers) {
        DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
        model.setRowCount(0);
        for (Customer c : customers) {
            model.addRow(new Object[]{
                    c.getCustomerId(),
                    c.getName(),
                    c.getPhone(),
                    c.getDiscount() + "%" // ← add this
            });
        }
    }

    // ── Click a row → fill the fields above ───────────────────────────
    private void setupTableClickListener() {
        tblCustomers.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblCustomers.getSelectedRow();
                if (row == -1) return;

                DefaultTableModel model = (DefaultTableModel) tblCustomers.getModel();
                selectedCustomerId = (int) model.getValueAt(row, 0);
                txtName.setText(model.getValueAt(row, 1).toString());
                txtPhone.setText(model.getValueAt(row, 2).toString());
                txtDiscount.setText(model.getValueAt(row, 3).toString());
            }
        });
    }

    // ── Button actions ─────────────────────────────────────────────────
    private void setupButtons() {

        // ADD
        btnAdd.addActionListener(e -> {
            if (!validateFields()) return;

            Customer c = new Customer();
            c.setName(txtName.getText().trim());
            c.setPhone(txtPhone.getText().trim());
            c.setDiscount(parseDiscount());

            boolean success = customerDAO.addCustomer(c);
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Customer added successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadAllCustomers();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to add customer.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // UPDATE
        btnUpdate.addActionListener(e -> {
            if (selectedCustomerId == -1) {
                JOptionPane.showMessageDialog(this,
                        "Please select a customer from the table first.",
                        "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!validateFields()) return;

            Customer c = new Customer();
            c.setCustomerId(selectedCustomerId);
            c.setName(txtName.getText().trim());
            c.setPhone(txtPhone.getText().trim());
            c.setDiscount(parseDiscount());

            boolean success = customerDAO.updateCustomer(c);
            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Customer updated successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadAllCustomers();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to update customer.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // DELETE
        btnDelete.addActionListener(e -> {
            if (selectedCustomerId == -1) {
                JOptionPane.showMessageDialog(this,
                        "Please select a customer from the table first.",
                        "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete this customer?",
                    "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                boolean success = customerDAO.deleteCustomer(selectedCustomerId);
                if (success) {
                    JOptionPane.showMessageDialog(this,
                            "Customer deleted successfully!",
                            "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadAllCustomers();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Failed to delete customer.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        // SEARCH
        btnSearch.addActionListener(e -> {
            String keyword = txtSearch.getText().trim();
            if (keyword.isEmpty()) {
                loadAllCustomers();
            } else {
                populateTable(customerDAO.searchCustomer(keyword));
            }
        });

        // Press Enter in search field
        txtSearch.addActionListener(e -> btnSearch.doClick());

        // CLEAR
        btnClear.addActionListener(e -> clearFields());
    }

    // ── Validate required fields ───────────────────────────────────────
    private boolean validateFields() {
        if (txtName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Customer name is required.",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return false;
        }
        if (txtPhone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Phone number is required.",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            txtPhone.requestFocus();
            return false;
        }
        return true;
    }

    private int parseDiscount() {
        try {
            int d = Integer.parseInt(txtDiscount.getText().trim());
            if (d < 0 || d > 100) return 0;
            return d;
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    // ── Clear all fields and reset selection ───────────────────────────
    private void clearFields() {
        txtName.setText("");
        txtPhone.setText("");
        txtDiscount.setText("0");
        txtSearch.setText("");
        selectedCustomerId = -1;
        tblCustomers.clearSelection();
    }

    private void createUIComponents() {
        // Required by IntelliJ GUI Designer - leave empty
    }
}