package com.posapp.ui;

import com.posapp.dao.ProductDAO;
import com.posapp.model.Product;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

public class InventoryForm extends JPanel {

    // ── Generated by IntelliJ - DO NOT redeclare ──────────────────────
    private JPanel mainPanel;
    private JPanel panelHeader;
    private JLabel lblTitle;
    private JLabel lblLowStockAlert;
    private JTextField txtSearch;
    private JButton btnSearch;
    private JButton btnShowAll;
    private JButton btnLowStock;
    private JTable tblInventory;
    private JTextField txtNewQty;
    private JButton btnUpdateStock;
    private JPanel panelBody;
    // ──────────────────────────────────────────────────────────────────

    private final ProductDAO productDAO = new ProductDAO();
    private int selectedProductId = -1;

    public InventoryForm() {
        setLayout(new BorderLayout());
        add(mainPanel, BorderLayout.CENTER);

        setupTable();
        loadAllProducts();
        setupButtons();
        setupTableClickListener();
    }

    // ── Set up JTable columns and style ───────────────────────────────
    private void setupTable() {
        String[] columns = {"ID", "Product Name", "Category", "Size", "Color", "Price ($)", "Stock", "Status"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblInventory.setModel(model);
        tblInventory.setDefaultEditor(Object.class, null); // read-only

        tblInventory.setRowHeight(28);
        tblInventory.setFont(new Font("SansSerif", Font.PLAIN, 12));
        tblInventory.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        tblInventory.getTableHeader().setBackground(new Color(26, 58, 107));
        tblInventory.getTableHeader().setForeground(Color.WHITE);
        tblInventory.setSelectionBackground(new Color(232, 240, 250));
        tblInventory.setGridColor(new Color(230, 230, 230));

        // Column widths
        tblInventory.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblInventory.getColumnModel().getColumn(1).setPreferredWidth(180);
        tblInventory.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblInventory.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblInventory.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblInventory.getColumnModel().getColumn(5).setPreferredWidth(80);
        tblInventory.getColumnModel().getColumn(6).setPreferredWidth(60);
        tblInventory.getColumnModel().getColumn(7).setPreferredWidth(80);

        // Custom renderer — red row for low stock
        tblInventory.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                           boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                String status = table.getModel().getValueAt(row, 7).toString();
                if ("LOW".equals(status)) {
                    if (!isSelected) {
                        c.setBackground(new Color(253, 235, 234));
                        c.setForeground(new Color(163, 45, 45));
                    }
                    if (column == 7) {
                        setForeground(new Color(198, 40, 40));
                        setFont(getFont().deriveFont(Font.BOLD));
                    }
                } else {
                    if (!isSelected) {
                        c.setBackground(row % 2 == 0 ? Color.WHITE : new Color(248, 250, 252));
                        c.setForeground(new Color(26, 26, 46));
                    }
                    if (column == 7) {
                        setForeground(new Color(46, 125, 82));
                        setFont(getFont().deriveFont(Font.BOLD));
                    }
                }
                return c;
            }
        });
    }

    // ── Load all products into inventory table ────────────────────────
    private void loadAllProducts() {
        populateTable(productDAO.getAllProducts());
    }

    // ── Fill table rows ────────────────────────────────────────────────
    private void populateTable(List<Product> products) {
        DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
        model.setRowCount(0);

        int lowCount = 0;
        for (Product p : products) {
            String status = p.isLowStock() ? "LOW" : "OK";
            if (p.isLowStock()) lowCount++;

            model.addRow(new Object[]{
                    p.getProductId(),
                    p.getProductName(),
                    p.getCategoryName(),
                    p.getSize(),
                    p.getColor(),
                    String.format("$%.2f", p.getPrice()),
                    p.getQuantity(),
                    status
            });
        }

        // Update alert label
        if (lowCount > 0) {
            lblLowStockAlert.setText("⚠  " + lowCount + " Low Stock Item(s) — Please restock soon!");
            lblLowStockAlert.setForeground(new Color(198, 40, 40));
        } else {
            lblLowStockAlert.setText("✔  All products are sufficiently stocked.");
            lblLowStockAlert.setForeground(new Color(46, 125, 82));
        }
    }

    // ── Click a table row → remember which product is selected ────────
    private void setupTableClickListener() {
        tblInventory.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tblInventory.getSelectedRow();
                if (row == -1) return;
                DefaultTableModel model = (DefaultTableModel) tblInventory.getModel();
                selectedProductId = (int) model.getValueAt(row, 0);
                String productName = model.getValueAt(row, 1).toString();
                int currentQty = (int) model.getValueAt(row, 6);
                txtNewQty.setText(String.valueOf(currentQty));
                txtNewQty.requestFocus();
                txtNewQty.selectAll();
            }
        });
    }

    // ── Button actions ─────────────────────────────────────────────────
    private void setupButtons() {

        // SEARCH
        btnSearch.addActionListener(e -> {
            String keyword = txtSearch.getText().trim();
            if (keyword.isEmpty()) {
                loadAllProducts();
            } else {
                populateTable(productDAO.searchProducts(keyword));
            }
        });
        txtSearch.addActionListener(e -> btnSearch.doClick());

        // SHOW ALL
        btnShowAll.addActionListener(e -> {
            txtSearch.setText("");
            loadAllProducts();
        });

        // LOW STOCK FILTER
        btnLowStock.addActionListener(e -> {
            List<Product> lowStock = productDAO.getLowStockProducts();
            if (lowStock.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No low stock items found. All products are well stocked!",
                        "No Low Stock", JOptionPane.INFORMATION_MESSAGE);
            } else {
                populateTable(lowStock);
            }
        });

        // UPDATE STOCK
        btnUpdateStock.addActionListener(e -> {
            if (selectedProductId == -1) {
                JOptionPane.showMessageDialog(this,
                        "Please click a product row first to select it.",
                        "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String qtyText = txtNewQty.getText().trim();
            if (qtyText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please enter the new quantity.",
                        "Missing Quantity", JOptionPane.WARNING_MESSAGE);
                txtNewQty.requestFocus();
                return;
            }

            int newQty;
            try {
                newQty = Integer.parseInt(qtyText);
                if (newQty < 0) {
                    JOptionPane.showMessageDialog(this,
                            "Quantity cannot be negative.",
                            "Invalid Quantity", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a whole number (e.g. 10, 50).",
                        "Invalid Input", JOptionPane.WARNING_MESSAGE);
                txtNewQty.requestFocus();
                return;
            }

            // Build a product object with just the updated quantity
            com.posapp.model.Product p = productDAO.getProductById(selectedProductId);
            if (p == null) {
                JOptionPane.showMessageDialog(this,
                        "Product not found in database.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            p.setQuantity(newQty);
            boolean success = productDAO.updateProduct(p);

            if (success) {
                JOptionPane.showMessageDialog(this,
                        "Stock updated successfully! New quantity: " + newQty,
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadAllProducts();
                txtNewQty.setText("");
                selectedProductId = -1;
                tblInventory.clearSelection();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Failed to update stock.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    private void createUIComponents() {
        // Required by IntelliJ GUI Designer
    }
}