package com.posapp.ui;

import com.posapp.dao.SaleDAO;
import com.posapp.model.Sale;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;

public class ReportForm extends JPanel {

    // ── Generated by IntelliJ - DO NOT redeclare ──────────────────────
    private JPanel mainPanel;
    private JPanel panelHeader;
    private JLabel lblTitle;
    private JPanel panelBody;
    private JButton btnDailyReport;
    private JButton btnMonthlyReport;
    private JButton btnTopProducts;
    private JTextField txtDate;
    private JButton btnFilter;
    private JTable tblReport;
    private JPanel panelSummary;
    private JLabel lblTotalSales;
    private JLabel lblTotalRevenue;
    // ──────────────────────────────────────────────────────────────────

    private final SaleDAO saleDAO = new SaleDAO();

    public ReportForm() {
        setLayout(new BorderLayout());
        add(mainPanel, BorderLayout.CENTER);

        setupTable();
        setupSummaryPanel();
        setupButtons();

        // Show today's report by default
        loadDailyReport(null);
    }

    // ── Style the summary panel and labels ────────────────────────────
    private void setupSummaryPanel() {
        panelSummary.setBackground(new Color(232, 240, 250));

        lblTotalSales.setFont(new Font("SansSerif", Font.BOLD, 13));
        lblTotalSales.setForeground(new Color(26, 58, 107));

        lblTotalRevenue.setFont(new Font("SansSerif", Font.BOLD, 13));
        lblTotalRevenue.setForeground(new Color(46, 125, 82));
    }

    // ── Update the two summary labels ─────────────────────────────────
    private void updateSummary(int salesCount, BigDecimal revenue) {
        lblTotalSales.setText("  Total Sales:  " + salesCount);
        lblTotalRevenue.setText("  Total Revenue:  $" + String.format("%.2f", revenue));
    }

    // ── Set up table columns ──────────────────────────────────────────
    private void setupTable() {
        String[] columns = {"Invoice No", "Customer", "Total ($)", "Date", "Payment"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblReport.setModel(model);
        tblReport.setDefaultEditor(Object.class, null);

        tblReport.setRowHeight(28);
        tblReport.setFont(new Font("SansSerif", Font.PLAIN, 12));
        tblReport.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        tblReport.getTableHeader().setBackground(new Color(26, 58, 107));
        tblReport.getTableHeader().setForeground(Color.WHITE);
        tblReport.setSelectionBackground(new Color(232, 240, 250));
        tblReport.setGridColor(new Color(230, 230, 230));

        tblReport.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblReport.getColumnModel().getColumn(1).setPreferredWidth(160);
        tblReport.getColumnModel().getColumn(2).setPreferredWidth(90);
        tblReport.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblReport.getColumnModel().getColumn(4).setPreferredWidth(100);
    }

    // ── Fill table with sales data ────────────────────────────────────
    private void populateSaleTable(List<Sale> sales) {
        // Reset to sale columns in case Top Products was shown before
        String[] columns = {"Invoice No", "Customer", "Total ($)", "Date", "Payment"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblReport.setModel(model);
        tblReport.setDefaultEditor(Object.class, null);
        tblReport.getTableHeader().setBackground(new Color(26, 58, 107));
        tblReport.getTableHeader().setForeground(Color.WHITE);

        BigDecimal totalRevenue = BigDecimal.ZERO;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");

        for (Sale sale : sales) {
            String dateStr = sale.getSaleDate() != null
                    ? sdf.format(sale.getSaleDate()) : "-";
            String customer = sale.getCustomerName() != null
                    ? sale.getCustomerName() : "Walk-in Customer";

            model.addRow(new Object[]{
                    sale.getInvoiceNo(),
                    customer,
                    "$" + String.format("%.2f", sale.getGrandTotal()),
                    dateStr,
                    sale.getPaymentMethod()
            });

            totalRevenue = totalRevenue.add(sale.getGrandTotal());
        }

        updateSummary(sales.size(), totalRevenue);
    }

    // ── Fill table for Top Products ───────────────────────────────────
    private void populateTopProducts(List<Object[]> rows) {
        String[] columns = {"Rank", "Product Name", "Category", "Qty Sold", "Revenue"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblReport.setModel(model);
        tblReport.setDefaultEditor(Object.class, null);
        tblReport.getTableHeader().setBackground(new Color(26, 58, 107));
        tblReport.getTableHeader().setForeground(Color.WHITE);

        int rank = 1;
        int totalQty = 0;
        BigDecimal totalRevenue = BigDecimal.ZERO;

        for (Object[] row : rows) {
            int qty = (int) row[2];
            BigDecimal rev = (BigDecimal) row[3];
            totalQty += qty;
            totalRevenue = totalRevenue.add(rev);

            model.addRow(new Object[]{
                    rank++,
                    row[0],
                    row[1],
                    qty,
                    "$" + String.format("%.2f", rev)
            });
        }

        lblTotalSales.setText("  Products: " + rows.size() + "  |  Total Qty Sold: " + totalQty);
        lblTotalRevenue.setText("  Total Revenue:  $" + String.format("%.2f", totalRevenue));
    }

    // ── Load daily report ─────────────────────────────────────────────
    private void loadDailyReport(String date) {
        List<Sale> sales = saleDAO.getSalesByDate(date);
        populateSaleTable(sales);

        String dateLabel = (date == null || date.isEmpty()) ? "Today" : date;
    }

    // ── Load monthly report ───────────────────────────────────────────
    private void loadMonthlyReport(String yearMonth) {
        List<Sale> sales = saleDAO.getSalesByMonth(yearMonth);
        populateSaleTable(sales);

        String monthLabel = (yearMonth == null || yearMonth.isEmpty()) ? "This Month" : yearMonth;
    }

    // ── Button actions ────────────────────────────────────────────────
    private void setupButtons() {

        btnDailyReport.addActionListener(e -> {
            txtDate.setText("");
            loadDailyReport(null);
        });

        btnMonthlyReport.addActionListener(e -> {
            txtDate.setText("");
            loadMonthlyReport(null);
        });

        btnTopProducts.addActionListener(e -> {
            txtDate.setText("");
            List<Object[]> topProducts = saleDAO.getTopSellingProducts(10);
            populateTopProducts(topProducts);
        });

        btnFilter.addActionListener(e -> {
            String input = txtDate.getText().trim();
            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a date (yyyy-MM-dd) or month (yyyy-MM).",
                        "Missing Input", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (input.length() == 7) {
                loadMonthlyReport(input);
            } else if (input.length() == 10) {
                loadDailyReport(input);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Format must be:\nyyyy-MM-dd for a day (e.g. 2026-07-14)\nyyyy-MM for a month (e.g. 2026-07)",
                        "Invalid Format", JOptionPane.WARNING_MESSAGE);
            }
        });

        txtDate.addActionListener(e -> btnFilter.doClick());
    }

    private void createUIComponents() {
        // Required by IntelliJ GUI Designer
    }
}