package com.posapp.ui;

import com.posapp.dao.CustomerDAO;
import com.posapp.dao.ProductDAO;
import com.posapp.dao.SaleDAO;
import com.posapp.model.Customer;
import com.posapp.model.Product;
import com.posapp.model.Sale;
import com.posapp.model.SaleDetail;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.MessageFormat;
import java.awt.Frame;
import java.awt.FlowLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

// ── NEW imports for auto PDF generation ─────────────────────────────
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfWriter;
// ─────────────────────────────────────────────────────────────────────

public class SalesPOSForm extends JPanel {

    // ── Generated by IntelliJ - DO NOT redeclare ──────────────────────
    private JPanel panelHeader;
    private JPanel mainPanel;
    private JLabel lblTitle;
    private JPanel panelLeft;
    private JPanel panelRight;
    private JTextField txtProductSearch;
    private JButton btnSearch;
    private JTable tblProducts;
    private JTextField txtQty;
    private JButton btnAddToCart;
    private JTable tblCart;
    private JButton btnCheckOut;
    private JButton btnClearCart;
    private JComboBox cmbCustomer;
    private JComboBox cmbPayment;
    private JLabel lblGrandTotal;
    private JTextField txtAmountPaid;
    private JLabel lblChange;
    private JButton btnRemove;
    private JTextField txtCustomerSearch;
    private JButton btnSearchCustomer;
    // ──────────────────────────────────────────────────────────────────

    private final ProductDAO productDAO = new ProductDAO();
    private final CustomerDAO customerDAO = new CustomerDAO();
    private final SaleDAO saleDAO = new SaleDAO();
    private int currentDiscount = 0; // tracks selected customer's discount

    // Cart items stored in memory
    private final List<SaleDetail> cartItems = new ArrayList<>();
    private BigDecimal grandTotal = BigDecimal.ZERO;

    // The logged-in employee id (passed from DashboardForm)
    private int employeeId;

    public SalesPOSForm(int employeeId) {
        this.employeeId = employeeId;
        setLayout(new BorderLayout());
        add(mainPanel, BorderLayout.CENTER);

        setupProductTable();
        setupCartTable();
        loadAllProducts();
        loadCustomers();
        setupPaymentMethods();
        setupButtons();
        setupProductTableClick();
        setupAmountPaidListener();
        setupCustomerListener();
        setupCustomerSearch();
    }

    // ── Product table (left side) ─────────────────────────────────────
    private void setupProductTable() {
        String[] columns = {"ID", "Product Name", "Size", "Color", "Price", "Stock"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblProducts.setModel(model);
        tblProducts.setDefaultEditor(Object.class, null);
        tblProducts.setRowHeight(26);
        tblProducts.setFont(new Font("SansSerif", Font.PLAIN, 11));
        tblProducts.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 11));
        tblProducts.getTableHeader().setBackground(new Color(26, 58, 107));
        tblProducts.getTableHeader().setForeground(Color.WHITE);
        tblProducts.setSelectionBackground(new Color(232, 240, 250));
        tblProducts.setGridColor(new Color(230, 230, 230));

        tblProducts.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblProducts.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblProducts.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblProducts.getColumnModel().getColumn(3).setPreferredWidth(60);
        tblProducts.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblProducts.getColumnModel().getColumn(5).setPreferredWidth(40);
    }

    // ── Cart table (right side) ───────────────────────────────────────
    private void setupCartTable() {
        String[] columns = {"Product Name", "Price", "Qty", "Subtotal"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        tblCart.setModel(model);
        tblCart.setDefaultEditor(Object.class, null);
        tblCart.setRowHeight(26);
        tblCart.setFont(new Font("SansSerif", Font.PLAIN, 11));
        tblCart.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 11));
        tblCart.getTableHeader().setBackground(new Color(26, 58, 107));
        tblCart.getTableHeader().setForeground(Color.WHITE);
        tblCart.setSelectionBackground(new Color(232, 240, 250));
        tblCart.setGridColor(new Color(230, 230, 230));

        tblCart.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblCart.getColumnModel().getColumn(1).setPreferredWidth(60);
        tblCart.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblCart.getColumnModel().getColumn(3).setPreferredWidth(70);
    }

    // ── Load all products into left table ─────────────────────────────
    private void loadAllProducts() {
        populateProductTable(productDAO.getAllProducts());
    }

    private void populateProductTable(List<Product> products) {
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.setRowCount(0);
        for (Product p : products) {
            model.addRow(new Object[]{
                    p.getProductId(),
                    p.getProductName(),
                    p.getSize(),
                    p.getColor(),
                    String.format("$%.2f", p.getPrice()),
                    p.getQuantity()
            });
        }
    }

    // ── Load customers into cmbCustomer ───────────────────────────────
    private void loadCustomers() {
        cmbCustomer.removeAllItems();
        cmbCustomer.addItem("-- Walk-in Customer --");
        List<Customer> customers = customerDAO.getAllCustomers();
        for (Customer c : customers) {
            cmbCustomer.addItem(c);
        }
    }

    private void setupCustomerSearch() {
        btnSearchCustomer.addActionListener(e -> {
            String keyword = txtCustomerSearch.getText().trim();
            if (keyword.isEmpty()) {
                loadCustomers(); // reset to show all
                return;
            }

            // Search customers by name or phone
            List<Customer> results = customerDAO.searchCustomer(keyword);
            cmbCustomer.removeAllItems();
            cmbCustomer.addItem("-- Walk-in Customer --");

            if (results.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No customer found with: " + keyword,
                        "Not Found", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (Customer c : results) {
                    cmbCustomer.addItem(c);
                }
                // Auto-select if only one result found
                if (results.size() == 1) {
                    cmbCustomer.setSelectedIndex(1);
                }
            }
        });

        // Press Enter in search field = same as clicking Find
        txtCustomerSearch.addActionListener(e -> btnSearchCustomer.doClick());
    }

    // ── Setup payment method dropdown ─────────────────────────────────
    private void setupPaymentMethods() {
        cmbPayment.removeAllItems();
        cmbPayment.addItem("Cash");
        cmbPayment.addItem("ABA Pay");
        cmbPayment.addItem("Wing Pay");
    }

    // ── Click product row → fill qty field ───────────────────────────
    private void setupProductTableClick() {
        tblProducts.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                txtQty.setText("1");
                txtQty.requestFocus();
                txtQty.selectAll();
            }
        });
    }

    // ── Live change calculation when amount paid is typed ────────────
    private void setupAmountPaidListener() {
        txtAmountPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                calculateChange();
            }
        });
    }

    private void setupCustomerListener() {
        cmbCustomer.addActionListener(e -> {
            Object selected = cmbCustomer.getSelectedItem();
            if (selected instanceof Customer) {
                Customer c = (Customer) selected;
                currentDiscount = c.getDiscount();
            } else {
                currentDiscount = 0;
            }
            refreshCart(); // recalculate total with new discount
        });
    }

    private void calculateChange() {
        try {
            String amountText = txtAmountPaid.getText().trim();
            if (amountText.isEmpty()) {
                lblChange.setText("$0.00");
                return;
            }
            BigDecimal amountPaid = new BigDecimal(amountText);
            BigDecimal change = amountPaid.subtract(grandTotal);
            if (change.compareTo(BigDecimal.ZERO) >= 0) {
                lblChange.setText("$" + String.format("%.2f", change));
                lblChange.setForeground(new Color(46, 125, 82));
            } else {
                lblChange.setText("-$" + String.format("%.2f", change.abs()));
                lblChange.setForeground(new Color(198, 40, 40));
            }
        } catch (NumberFormatException ex) {
            lblChange.setText("$0.00");
        }
    }

    // ── Update cart table and grand total label ───────────────────────
    private void refreshCart() {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        model.setRowCount(0);
        grandTotal = BigDecimal.ZERO;

        for (SaleDetail item : cartItems) {
            model.addRow(new Object[]{
                    item.getProductName(),
                    "$" + String.format("%.2f", item.getPrice()),
                    item.getQuantity(),
                    "$" + String.format("%.2f", item.getSubtotal())
            });
            grandTotal = grandTotal.add(item.getSubtotal());
        }

        // Apply VIP discount if any
        if (currentDiscount > 0) {
            BigDecimal discountAmount = grandTotal
                    .multiply(new BigDecimal(currentDiscount))
                    .divide(new BigDecimal(100));
            BigDecimal discountedTotal = grandTotal.subtract(discountAmount);

            lblGrandTotal.setText("$" + String.format("%.2f", discountedTotal)
                    + "  (" + currentDiscount + "% VIP discount applied)");
            lblGrandTotal.setForeground(new Color(46, 125, 82));
            grandTotal = discountedTotal; // use discounted total for checkout
        } else {
            lblGrandTotal.setText("$" + String.format("%.2f", grandTotal));
            lblGrandTotal.setForeground(new Color(26, 58, 107));
        }

        calculateChange();
    }

    // ── Generate receipt PDF automatically (no dialogs, no manual filename) ──
    private File generateReceiptPdf(String receiptText, String invoiceNo) throws Exception {
        // Save into a "receipts" folder next to the app, auto-created if missing
        File folder = new File("receipts");
        if (!folder.exists()) folder.mkdirs();

        File file = new File(folder, invoiceNo + ".pdf");

        String[] lines = receiptText.split("\n");

        // 80 mm thermal paper width in points
        float widthPt = 80f * 2.83465f;   // ≈ 226.77 pt

        // Courier 8 pt monospaced: each char ≈ 4.8 pt wide
        float charWidthPt = 8f * 0.6f;
        int maxChars = 40;                  // longest line (separator, header, footer)
        float textWidthPt = maxChars * charWidthPt;  // 192 pt

        // Center the text block horizontally
        float hMargin = (widthPt - textWidthPt) / 2f;
        if (hMargin < 0) hMargin = 0;

        float fontSize = 8f;
        float lineHeight = fontSize * 1.5f;   // 12 pt per line
        float topMargin = 8f;
        float bottomMargin = 8f;

        // Total page height: exact lines + margins + safety buffer
        float heightPt = (lines.length * lineHeight) + topMargin + bottomMargin + 20f;

        // Create document with ZERO margins — we position every line ourselves
        Document document = new Document(new Rectangle(widthPt, heightPt), 0, 0, 0, 0);
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(file));
        document.open();

        // Use explicit text object for guaranteed rendering
        PdfContentByte cb = writer.getDirectContent();
        BaseFont bf = BaseFont.createFont(BaseFont.COURIER, BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);

        cb.beginText();
        cb.setFontAndSize(bf, fontSize);
        cb.setColorFill(BaseColor.BLACK);

        float y = heightPt - topMargin;
        for (String line : lines) {
            // setTextMatrix(1,0,0,1,x,y) = identity scale + translate to (x,y)
            cb.setTextMatrix(1, 0, 0, 1, hMargin, y);
            cb.showText(line);
            y -= lineHeight;
        }

        cb.endText();
        document.close();
        return file;
    }

    // ── Button actions ────────────────────────────────────────────────
    private void setupButtons() {

        // SEARCH
        btnSearch.addActionListener(e -> {
            String keyword = txtProductSearch.getText().trim();
            if (keyword.isEmpty()) {
                loadAllProducts();
            } else {
                populateProductTable(productDAO.searchProducts(keyword));
            }
        });
        txtProductSearch.addActionListener(e -> btnSearch.doClick());

        // ADD TO CART
        btnAddToCart.addActionListener(e -> {
            int row = tblProducts.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this,
                        "Please select a product from the list first.",
                        "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Parse quantity
            int qty;
            try {
                qty = Integer.parseInt(txtQty.getText().trim());
                if (qty <= 0) throw new NumberFormatException();
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Please enter a valid quantity (e.g. 1, 2, 3).",
                        "Invalid Quantity", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get product details from table
            DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
            int productId = (int) model.getValueAt(row, 0);
            String productName = model.getValueAt(row, 1).toString();
            int stock = (int) model.getValueAt(row, 5);

            // Check stock
            if (qty > stock) {
                JOptionPane.showMessageDialog(this,
                        "Not enough stock! Available: " + stock,
                        "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Get price
            String priceStr = model.getValueAt(row, 4).toString().replace("$", "");
            BigDecimal price = new BigDecimal(priceStr);
            BigDecimal subtotal = price.multiply(new BigDecimal(qty));

            // Check if product already in cart → increase quantity
            for (SaleDetail item : cartItems) {
                if (item.getProductId() == productId) {
                    int newQty = item.getQuantity() + qty;
                    if (newQty > stock) {
                        JOptionPane.showMessageDialog(this,
                                "Not enough stock! Available: " + stock,
                                "Insufficient Stock", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    item.setQuantity(newQty);
                    item.setSubtotal(price.multiply(new BigDecimal(newQty)));
                    refreshCart();
                    return;
                }
            }

            // New item — add to cart
            SaleDetail detail = new SaleDetail(productId, productName, qty, price, subtotal);
            cartItems.add(detail);
            refreshCart();
        });

        // REMOVE FROM CART
        btnRemove.addActionListener(e -> {
            int row = tblCart.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this,
                        "Please select an item from the cart first.",
                        "No Selection", JOptionPane.WARNING_MESSAGE);
                return;
            }
            cartItems.remove(row);
            refreshCart();
        });

        // CLEAR CART
        btnClearCart.addActionListener(e -> {
            cartItems.clear();
            txtAmountPaid.setText("");
            lblChange.setText("$0.00");
            refreshCart();
        });

        // CHECKOUT
        btnCheckOut.addActionListener(e -> {
            if (cartItems.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Cart is empty. Please add products first.",
                        "Empty Cart", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validate amount paid
            BigDecimal amountPaid;
            try {
                amountPaid = new BigDecimal(txtAmountPaid.getText().trim());
                if (amountPaid.compareTo(grandTotal) < 0) {
                    JOptionPane.showMessageDialog(this,
                            "Amount paid is less than the grand total ($"
                                    + String.format("%.2f", grandTotal) + ").",
                            "Insufficient Payment", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Please enter the amount paid.",
                        "Missing Payment", JOptionPane.WARNING_MESSAGE);
                txtAmountPaid.requestFocus();
                return;
            }

            BigDecimal change = amountPaid.subtract(grandTotal);
            String paymentMethod = cmbPayment.getSelectedItem().toString();

            // Build Sale object
            Sale sale = new Sale();
            sale.setInvoiceNo(saleDAO.generateInvoiceNo());
            sale.setSaleDate(new java.sql.Timestamp(new Date().getTime()));
            sale.setEmployeeId(employeeId);
            sale.setGrandTotal(grandTotal);
            sale.setAmountPaid(amountPaid);
            sale.setChangeDue(change);
            sale.setPaymentMethod(paymentMethod);

            // Set customer (null = walk-in)
            Object selectedCustomer = cmbCustomer.getSelectedItem();
            if (selectedCustomer instanceof Customer) {
                sale.setCustomerId(((Customer) selectedCustomer).getCustomerId());
                sale.setCustomerName(((Customer) selectedCustomer).getName());
            } else {
                sale.setCustomerId(null);
                sale.setCustomerName("Walk-in Customer");
            }

            // Save to database
            int saleId = saleDAO.checkout(sale, cartItems);

            if (saleId > 0) {
                // Show receipt
                showReceipt(sale, saleId);

                // Clear cart
                cartItems.clear();
                txtAmountPaid.setText("");
                lblChange.setText("$0.00");
                refreshCart();
                loadAllProducts(); // refresh stock

            } else {
                JOptionPane.showMessageDialog(this,
                        "Checkout failed. Please try again.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    // ── Receipt dialog ────────────────────────────────────────────────
    private void showReceipt(Sale sale, int saleId) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        StringBuilder receipt = new StringBuilder();

        receipt.append("========================================\n");
        receipt.append("        CLOTHING STORE POS SYSTEM       \n");
        receipt.append("========================================\n");
        receipt.append("Invoice : ").append(sale.getInvoiceNo()).append("\n");
        receipt.append("Date    : ").append(sdf.format(new Date())).append("\n");
        receipt.append("Customer: ").append(sale.getCustomerName()).append("\n");
        receipt.append("Payment : ").append(sale.getPaymentMethod()).append("\n");
        receipt.append("----------------------------------------\n");
        receipt.append(String.format("%-22s %6s %8s\n", "Product", "Qty", "Total"));
        receipt.append("----------------------------------------\n");

        for (SaleDetail item : cartItems) {
            receipt.append(String.format("%-22s %6d %8s\n",
                    item.getProductName(),
                    item.getQuantity(),
                    "$" + String.format("%.2f", item.getSubtotal())));
        }

        receipt.append("----------------------------------------\n");
        if (currentDiscount > 0) {
            receipt.append(String.format("%-22s %15s\n", "DISCOUNT:",
                    currentDiscount + "% VIP"));
        }
        receipt.append(String.format("%-22s %15s\n", "GRAND TOTAL:",
                "$" + String.format("%.2f", sale.getGrandTotal())));
        receipt.append(String.format("%-22s %15s\n", "AMOUNT PAID:",
                "$" + String.format("%.2f", sale.getAmountPaid())));
        receipt.append(String.format("%-22s %15s\n", "CHANGE:",
                "$" + String.format("%.2f", sale.getChangeDue())));
        receipt.append("========================================\n");
        receipt.append("       Thank you for shopping!          \n");
        receipt.append("========================================\n");

        // ── Show receipt in scrollable dialog ─────────────────────────
        JTextArea textArea = new JTextArea(receipt.toString());
        textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        textArea.setEditable(false);
        textArea.setBackground(Color.WHITE);
        textArea.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));

        JPanel paperWrapper = new JPanel(new GridBagLayout());
        paperWrapper.setBackground(new Color(230, 230, 230));
        paperWrapper.add(textArea);

        JScrollPane scrollPane = new JScrollPane(paperWrapper);
        scrollPane.setPreferredSize(new Dimension(400, 420));
        scrollPane.getViewport().setBackground(new Color(230, 230, 230));
        scrollPane.setBorder(BorderFactory.createEmptyBorder());

        // ── Buttons: Print + Close ─────────────────────────────────────
        JButton btnPrint = new JButton("🖨  Print Receipt");
        btnPrint.setBackground(new Color(26, 58, 107));
        btnPrint.setForeground(Color.WHITE);
        btnPrint.setFocusPainted(false);
        btnPrint.setFont(new Font("SansSerif", Font.BOLD, 12));

        JButton btnClose = new JButton("Close");
        btnClose.setFont(new Font("SansSerif", Font.PLAIN, 12));

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(btnPrint);
        buttonPanel.add(btnClose);

        JPanel receiptPanel = new JPanel(new BorderLayout());
        receiptPanel.add(scrollPane, BorderLayout.CENTER);
        receiptPanel.add(buttonPanel, BorderLayout.SOUTH);

        JDialog dialog = new JDialog(
                (Frame) SwingUtilities.getWindowAncestor(this),
                "Receipt - " + sale.getInvoiceNo(),
                true
        );
        dialog.setContentPane(receiptPanel);
        dialog.setSize(480, 500);
        dialog.setLocationRelativeTo(this);

        // Print button action
        btnPrint.addActionListener(e -> {
            try {
                File pdfFile = generateReceiptPdf(receipt.toString(), sale.getInvoiceNo());
                JOptionPane.showMessageDialog(dialog,
                        "Receipt saved automatically:\n" + pdfFile.getAbsolutePath(),
                        "Receipt Saved", JOptionPane.INFORMATION_MESSAGE);

                Desktop.getDesktop().open(pdfFile);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(dialog,
                        "Failed to save receipt: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        });

        btnClose.addActionListener(e -> dialog.dispose());
        dialog.setVisible(true);
    }

    private void createUIComponents() {
        // Required by IntelliJ GUI Designer
    }
}